language: go

go:
- 1.3
- 1.4
- tip

before_install:
- go get -u github.com/axw/gocov/gocov
- go get -u github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover

matrix:
  allow_failures:
  - go: tip

install:
- go get -t -d -v ./...

script:
- go build -v $(go list ./... | grep -v vendor)
- go test -v $(go list ./... | grep -v vendor)
- make cover
- goveralls -service=travis-ci -v -coverprofile=profile.out