language: go

sudo: false

go:
- "1.10"
- tip

before_install:
- go get -u github.com/axw/gocov/gocov
- go get -u github.com/mattn/goveralls
- go get -u golang.org/x/tools/cmd/cover
- go get -u github.com/alecthomas/gometalinter
- gometalinter --install

addons:
  apt:
    packages:
      - graphviz

matrix:
  allow_failures:
  - go: tip

script:
- make build
- make test
- make lint
- make examples
- make cover
- goveralls -service=travis-ci -v -covermode=count -coverprofile=profile.out
