language: go

sudo: false

go:
- "1.10"
- tip

before_install:
- go get -u github.com/imdario/mergo
- go get -u github.com/axw/gocov/gocov
- go get -u github.com/mattn/goveralls
- go get -u golang.org/x/tools/cmd/cover
- go get -u gopkg.in/alecthomas/gometalinter.v2
- gometalinter.v2 --install || true
- go get honnef.co/go/tools/cmd/megacheck # use alternative megacheck install URL

addons:
  apt:
    packages:
      - graphviz

matrix:
  allow_failures:
  - go: tip

script:
- make build
- make test
- make lint
- make examples
- make cover
- goveralls -service=travis-ci -v -covermode=count -coverprofile=profile.out
