version: 2.0
jobs:
  build:
    docker:
    - image: golang:1.8
    working_directory: /go/src/github.com/moul/advanced-ssh-config
    steps:
      - checkout
      - run: make
      - run: make test
